---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2026/4/26 19:42
---
--[[local likeKey = 'blog:liked:' .. ARGV[2]
local likeCount = 'blog:likeCount:' .. ARGV[2]
local userId = ARGV[1]
local blogId = ARGV[2]

if redis.call('SISMEMBER', likeKey, userId)==1 then
    redis.call('DECRBY', likeCount, 1)
    redis.call('SREM', likeKey, userId)
    return 1
    end
redis.call('INCRBY', likeCount, 1)
redis.call('SADD', likeKey, userId)
return 0]]

local likeKey = 'blog:liked:' .. ARGV[2]
local userId = ARGV[1]
local blogId = ARGV[2]
local score = tonumber(ARGV[3])
local exist=redis.call('ZSCORE', likeKey, userId)

if exist==false then
    redis.call('ZADD', likeKey, score,userId)
    return 0
end
redis.call('ZREM', likeKey,userId)
return 1



