---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2026/5/20 22:04
---

local productId = ARGV[1]
local quantity= tonumber(ARGV[2])
local stockKey = 'product:stock:id' .. productId
local stock = tonumber(redis.call('GET', stockKey))
if stock == nil or stock <quantity then
    return 1  -- 库存不足
end
--预减库存
redis.call("DECRBY",stockKey,quantity)
return 2
