
-- 优惠券 ID
local voucherId = ARGV[1]
-- 用户 ID
local userId=ARGV[2]
-- 订单 ID
local orderId = ARGV[3]
-- 库存 key
local stockkey = 'seckill:stock:' .. voucherId
-- 订单 key
local orderkey = 'seckill:order:' .. voucherId
-- 1. 获取并判断库存
local stock = tonumber(redis.call('GET', stockkey))
if stock == nil or stock <= 0 then
    return 1  -- 库存不足
end

-- 2. 判断用户是否已购买（使用 SET 的 SISMEMBER）
if redis.call('SISMEMBER', orderkey,userId) == 1 then
    return 2  -- 已经购买过，违反一人一单
end

-- 3. 预减库存（String 类型的 DECRBY）
redis.call('DECRBY', stockkey, 1)

-- 4. 将用户添加到已购集合（使用 SET 的 SADD）
redis.call('SADD', orderkey, userId)

-- 5 发送消息给消息队列
redis.call('XADD', 'stream.order', '*', 'userId', userId, 'voucherId', voucherId,'id' ,orderId )
return 0  -- 秒杀成功---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2026/4/25 20:33
---