---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2026/4/23 14:21
---
if (redis.call('get', KEYS[1]) == ARGV[1]) then--验证锁的持有者是否一致
return redis.call('del', KEYS[1])
end
return 0